name: rust setup
description: "Setup rust and dependencies cache"

inputs:
  cwd:
    description: "Changes node's `process.cwd()` if the project is not located on the root. Default to `process.cwd()`."
    required: false
    default: "."

  cache-prefix:
    description: "Add a specific cache-prefix."
    required: false
    default: "ci"

runs:
  using: "composite"

  steps:
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        target: ${{ env.RUST_TOOLCHAIN_TARGET }}

    - name: Setup rust dependencies cache
      uses: Swatinem/rust-cache@v2.7.8
      with:
        prefix-key: rust-cache-${{ inputs.cache-prefix }}
        shared-key: ${{ hashFiles(format('{0}/Cargo.lock', inputs.cwd)) }}
        key: ""
