version: 2

updates:
  # Cargo crates
  - package-ecosystem: "cargo"
    directories:
      - "/"
    schedule:
      interval: "monthly"
      time: "03:00"
      timezone: "Asia/Tokyo"
    labels:
      - "Type: Dependencies"
    assignees:
      - "RShirohara"
    open-pull-requests-limit: 10

    # node.js modules
  - package-ecosystem: "npm"
    directories:
      - "/"
    schedule:
      interval: "monthly"
      time: "03:00"
      timezone: "Asia/Tokyo"
    labels:
      - "Type: Dependencies"
    assignees:
      - "RShirohara"
    versioning-strategy: increase
    open-pull-requests-limit: 10

  # Terraform functions
  - package-ecosystem: "terraform"
    directories:
      - "/terraform/**/*"
    schedule:
      interval: "monthly"
      time: "03:00"
      timezone: "Asia/Tokyo"
    labels:
      - "Type: Dependencies"
    assignees:
      - "RShirohara"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/*"
    schedule:
      interval: "monthly"
      time: "03:00"
      timezone: "Asia/Tokyo"
    labels:
      - "Type: CI"
      - "Type: Dependencies"
    assignees:
      - "RShirohara"
