[package]
name = "masto-to-tw"
description = "Sync Mastodon posts to Twitter."
license = "MIT"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
futures = { version = "0.3.30", default-features = false }
getrandom = { version = "0.2.15", features = ["js"] }
reqwest = { version = "0.12.5", features = ["stream"] }
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.122"
tokio = { version = "1.39.2", default-features = false, features = ["io-util"] }
tokio-util = { version = "0.7.11", default-features = false, features = ["io"] }
twapi-v2 = { version = "0.14.2", features = ["oauth10a", "upload"] }
worker = "0.3.2"

[profile.release]
opt-level = "s"
lto = true
strip = true
codegen-units = 1
