[package]
name = "masto-to-tw"
description = "Sync Mastodon posts to Twitter."
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = "0.1.0"

[profile.release]
opt-level = "s"
lto = true
strip = true
codegen-units = 1
