name = "masto-to-tw"
main = "build/worker/shim.mjs"
compatibility_date = "2023-12-01"

[build]
command = """
export PATH="${PATH}:$(realpath ./node_modules/.bin):${CARGO_HOME:-~/.cargo}/bin"
cargo install -q worker-build && worker-build --release
"""

[[kv_namespaces]]
binding = "MASTO_TO_TW"
# Set created kv namespace id
id = "testId"

[triggers]
crons = ["*/5 * * * *"]

[env.dev]
build = { command = """
export PATH="${PATH}:$(realpath ./node_modules/.bin):${CARGO_HOME:-~/.cargo}/bin"
cargo install -q worker-build && worker-build --dev
""" }

[[env.dev.kv_namespaces]]
binding = "MASTO_TO_TW"
id = "testId"
