name = "masto-to-tw"
main = "build/worker/shim.mjs"
compatibility_date = "2023-12-01"

[build]
command = """
export PATH="${PATH}:$(realpath ./node_modules/.bin):${CARGO_HOME:-~/.cargo}/bin"
cargo install -q worker-build && worker-build --release
"""

[env.dev]
build = { command = """
export PATH="${PATH}:$(realpath ./node_modules/.bin):${CARGO_HOME:-~/.cargo}/bin"
cargo install -q worker-build && worker-build --dev
""" }
